# Generated by Django 2.2.5 on 2019-09-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
