# Generated by Django 2.2.5 on 2019-10-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20190927_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='image_main',
            field=models.CharField(default=None, max_length=200, verbose_name='Imagem Principal'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(default=None, max_length=100, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='slug',
            field=models.SlugField(default=None, max_length=300, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(default=None, max_length=100, verbose_name='Identificador'),
        ),
    ]
