# Generated by Django 2.2.7 on 2019-11-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20190927_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='main_image',
            field=models.FileField(default=None, upload_to='static/media/%Y/%m/%d/', verbose_name='Imagem Principal'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(default=None, max_length=100, unique=True, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='slug',
            field=models.SlugField(default=None, max_length=300, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(default=None, max_length=100, verbose_name='Identificador'),
        ),
    ]
