# Generated by Django 2.2.5 on 2019-10-03 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20191003_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='image_main',
            new_name='imagemain',
        ),
    ]
