# Generated by Django 2.2.7 on 2019-11-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20191110_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='main_image',
            field=models.FileField(default=None, upload_to='static/media/%Y-%m-%d/', verbose_name='Imagem Principal'),
        ),
    ]
