# Generated by Django 2.2.5 on 2019-10-03 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20191003_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='imagemain',
            new_name='main_image',
        ),
    ]
