# Generated by Django 2.2.7 on 2019-11-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_auto_20191110_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='main_image',
            field=models.FileField(default=None, upload_to='images/', verbose_name='Imagem Principal'),
        ),
    ]
