# Generated by Django 2.2.7 on 2019-11-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_auto_20191118_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='slug',
            field=models.FileField(default=None, upload_to='images/', verbose_name='Identificador'),
        ),
    ]
