# Generated by Django 2.2.7 on 2019-12-04 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_auto_20191119_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.SlugField(default=None, max_length=100, unique=True, verbose_name='Quantidade')),
                ('preco', models.DecimalField(decimal_places=2, default=None, max_digits=8, verbose_name='Preço')),
                ('total', models.DecimalField(decimal_places=2, default=None, max_digits=8, verbose_name='Total')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Modificado em')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.Produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Carrinho',
                'verbose_name_plural': 'Carrinho',
                'ordering': ['id'],
            },
        ),
    ]
