# Generated by Django 2.2.7 on 2019-12-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_carrinho_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='total',
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='quantidade',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
        ),
    ]
